/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import healthcare.System1;
import javax.swing.JPanel;
import healthcare.HospitalCity;
import healthcare.HospitalCities;
import java.awt.CardLayout;
import java.util.ArrayList;


/**
 *
 * @author mynenidivya
 */
public class CityPanel extends javax.swing.JPanel {
    private System1 System;
    private JPanel displayJpanel;


    /**
     * Creates new form HospitalCityPanel
     */
    public CityPanel(JPanel displayJPanel, System1 System) {
        initComponents();
        this.System = System;
        this.displayJpanel =displayJPanel;
        initializeCities();
    }
     private void initializeCities() {
        
        cityJComboBox.removeAllItems();
        ArrayList<HospitalCity> cities = HospitalCities.getCitiesList();
        for(HospitalCity city:cities){
            cityJComboBox.addItem(city.getCityName());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageSystemJLabel = new javax.swing.JLabel();
        chooseCityJLabel = new javax.swing.JLabel();
        cityJComboBox = new javax.swing.JComboBox<>();
        btnnext = new javax.swing.JButton();

        manageSystemJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        manageSystemJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageSystemJLabel.setText("City Health Care System");

        chooseCityJLabel.setText("City :");

        cityJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJComboBoxActionPerformed(evt);
            }
        });

        btnnext.setText("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(manageSystemJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(chooseCityJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnnext)
                            .addComponent(cityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(manageSystemJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseCityJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(btnnext)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cityJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJComboBoxActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here:
        String selectedCity = String.valueOf(cityJComboBox.getSelectedItem());
        java.lang.System.out.println(selectedCity);

        HospitalPanel hospital = new HospitalPanel(displayJpanel,System, selectedCity);
        displayJpanel.add("ManagePanel", hospital);
        CardLayout layout = (CardLayout) displayJpanel.getLayout();
        layout.next(displayJpanel);
    }//GEN-LAST:event_btnnextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnext;
    private javax.swing.JLabel chooseCityJLabel;
    private javax.swing.JComboBox<String> cityJComboBox;
    private javax.swing.JLabel manageSystemJLabel;
    // End of variables declaration//GEN-END:variables
}
