/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import javax.swing.JPanel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import healthcare.Community;
import healthcare.House;
import healthcare.System;

/**
 *
 * @author mynenidivya
 */
public class HousePanel extends javax.swing.JPanel {

    /**
     * Creates new form House
     */
     private JPanel displayJPanel;
    private System system;
    private Community Community;

    public HousePanel(JPanel displayJPanel, System system, Community Community) {
        this.displayJPanel = displayJPanel;
        this.system = system;
        this.Community = Community;
        initComponents();
        populateHouses();
    }
      private String formateDate(Date date) {
       String Formate="yyyy-mm-dd hh:mm:ss";
       
       SimpleDateFormat Simple=new SimpleDateFormat(Formate);
       return Simple.format(date);
    }
      String regxName = "^[a-zA-Z\\s]+$";
    String regxNum= "^[0-9]*$";
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();
        updateJButton = new javax.swing.JButton();
        lblstreetname = new javax.swing.JLabel();
        lblhousename = new javax.swing.JLabel();
        lblcountry = new javax.swing.JLabel();
        goJButton = new javax.swing.JButton();
        txthousename = new javax.swing.JTextField();
        housesJLabel = new javax.swing.JLabel();
        btnresetfields = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        housesJTable = new javax.swing.JTable();
        txtstate = new javax.swing.JTextField();
        txtcountry = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        backJButton.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        backJButton.setText("previous");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        addJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPackage/Save.png"))); // NOI18N
        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPackage/delete.png"))); // NOI18N
        deleteJButton.setText("Delete");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        updateJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPackage/edit.png"))); // NOI18N
        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        lblstreetname.setText("State : ");

        lblhousename.setText("House Name : ");

        lblcountry.setText("Country : ");

        goJButton.setText("Open");
        goJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goJButtonActionPerformed(evt);
            }
        });

        txthousename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthousenameActionPerformed(evt);
            }
        });

        housesJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        housesJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        housesJLabel.setText("Houses Present");

        btnresetfields.setText("Reset ");
        btnresetfields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetfieldsActionPerformed(evt);
            }
        });

        housesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "House Name", "State", "Country"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        housesJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                housesJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(housesJTable);

        txtstate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstateActionPerformed(evt);
            }
        });

        txtcountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblstreetname)
                                    .addComponent(lblhousename)
                                    .addComponent(lblcountry))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtstate, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txthousename)
                                    .addComponent(txtcountry)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addJButton)
                                .addGap(18, 18, 18)
                                .addComponent(updateJButton)
                                .addGap(33, 33, 33)
                                .addComponent(deleteJButton)))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(housesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goJButton)
                .addGap(30, 30, 30)
                .addComponent(btnresetfields)
                .addGap(348, 348, 348))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(housesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backJButton))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthousename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblhousename, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblstreetname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcountry, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addJButton)
                            .addComponent(updateJButton)
                            .addComponent(deleteJButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goJButton)
                    .addComponent(btnresetfields))
                .addContainerGap(141, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        displayJPanel.remove(this);
        CardLayout cardLayout =  (CardLayout) displayJPanel.getLayout();
        cardLayout.previous(displayJPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        if (txthousename.getText().isBlank() && txtstate.getText().isBlank() && txtcountry.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Please enter valid House details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) housesJTable.getModel();

        for(House house:Community.getHouses()){
            if (txthousename.getText().equals(house.getHouseName())){
                JOptionPane.showMessageDialog(this, "House name already exists\nPlease enter a different house name");
                return;
            }
        }
        if (txthousename.getText().matches(regxName) && txtstate.getText().matches(regxName)&&txtcountry.getText().matches(regxName)){

        House house = new House(txthousename.getText(), txtstate.getText(), txtcountry.getText());
        Community.getHouses().add(house);
        populateHouses();

        txthousename.setText("");
        txtstate.setText("");
        txtcountry.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Please enter valid details");
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        int selectedRowIndex = housesJTable.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) housesJTable.getModel();
        House house = (House) model.getValueAt(selectedRowIndex, 0);

        Community.getHouses().remove(house);

        txthousename.setText("");
        txtstate.setText("");
        txtcountry.setText("");

        JOptionPane.showMessageDialog(this, "House deleted successfully");
        populateHouses();
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        int selectedRowIndex = housesJTable.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) housesJTable.getModel();
        House house = (House) model.getValueAt(selectedRowIndex, 0);

        if (house.getHouseName().equals(txthousename.getText()) && house.getState().equals(txtstate.getText()) && house.getCountry().equals(txtcountry.getText())){
            JOptionPane.showMessageDialog(this, "No new values entered\nPlease enter a new house name");
            return;
        }else if (txthousename.getText().equals("") && txtstate.getText().equals("") && txtcountry.getText().equals("")){
            JOptionPane.showMessageDialog(this, "House Name is blank\nPlease enter a valid house name");
            return;
        }
        else{
            if (txthousename.getText().matches(regxName) && txtstate.getText().matches(regxName)&&txtcountry.getText().matches(regxName)){
            house.setHouseName(txthousename.getText());
            house.setState(txtstate.getText());
            house.setCountry(txtcountry.getText());

            JOptionPane.showMessageDialog(this, "House updated successfully");
            populateHouses();

            txthousename.setText("");
            txtstate.setText("");
            txtcountry.setText("");
        }else{
                JOptionPane.showMessageDialog(this, "Enter valid details");
            }
        }
    }
    private void populateHouses() {
        
        DefaultTableModel model = (DefaultTableModel) housesJTable.getModel();
        model.setRowCount(0);
        
        for(House house:Community.getHouses()){
            Object[] row = new Object[3];
            row[0] = house;
            row[1] = house.getState();
            row[2] = house.getCountry();
            
            model.addRow(row);
        }
    
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void goJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = housesJTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(this, "Please Select any Community to View the Houses");
            return;
        }

        showPersonsInCommunity(selectedRow);
    }
         private void showPersonsInCommunity(int selectedRow) {
        
        DefaultTableModel model = (DefaultTableModel) housesJTable.getModel();
        House house = (House) model.getValueAt(selectedRow, 0);
        if (house.getPersons().isEmpty()==true){
            JOptionPane.showMessageDialog(this, "No persons available under this House");
        }navigateToPersons(house);
    }
    
    private void navigateToPersons(House house) {
        
        PersonPanel personPanel = new PersonPanel(displayJPanel, house);
        displayJPanel.add("PersonsInformation", personPanel);
        CardLayout cardLayout = (CardLayout) displayJPanel.getLayout();
        cardLayout.next(displayJPanel);
    
    }//GEN-LAST:event_goJButtonActionPerformed

    private void txthousenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthousenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthousenameActionPerformed

    private void btnresetfieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetfieldsActionPerformed

        txthousename.setText("");
        txtstate.setText("");
        txtcountry.setText("");
    }//GEN-LAST:event_btnresetfieldsActionPerformed

    private void housesJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_housesJTableMouseClicked
        int selectedRowIndex = housesJTable.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) housesJTable.getModel();
        House house = (House) model.getValueAt(selectedRowIndex, 0);

        txthousename.setText(house.getHouseName());
        txtstate.setText(house.getState());
        txtcountry.setText(house.getCountry());
    }//GEN-LAST:event_housesJTableMouseClicked

    private void txtstateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstateActionPerformed

    private void txtcountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcountryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnresetfields;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JButton goJButton;
    private javax.swing.JLabel housesJLabel;
    private javax.swing.JTable housesJTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcountry;
    private javax.swing.JLabel lblhousename;
    private javax.swing.JLabel lblstreetname;
    private javax.swing.JTextField txtcountry;
    private javax.swing.JTextField txthousename;
    private javax.swing.JTextField txtstate;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
