/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import healthcare.Doctor;
import healthcare.Hospital;
import healthcare.HospitalCity;
import healthcare.System1;
import java.awt.CardLayout;
import java.awt.Panel;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author mynenidivya
 */
public class OPPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form PatientPanel1
     */
    private JPanel displayJpanel;
    private System1 system;
    private HospitalCity city;
    private Hospital hospital;
   
    
    public OPPanel1(JPanel displayJpanel,System1 system) {
        this.displayJpanel=displayJpanel;
        this.system=system;
        initComponents();
        initializeCities();
        initializehospitals();
    }
    private void initializeCities() {
        
        List<HospitalCity> cities = system.getCities();
        for(HospitalCity city:cities){
            cityJComboBox.addItem(city.getCityName());
        }
    }
    private void initializehospitals() {
        HospitalJComboBox.removeAllItems();
        String selectedCityName = (String) cityJComboBox.getSelectedItem();
        for(HospitalCity city : system.getCities()) {
            if(city.getCityName().equalsIgnoreCase(selectedCityName)){
                this.city = city;                
                for(Hospital hospital: city.getHospitals()){
                    HospitalJComboBox.addItem(hospital.getHospitalName());
                    
                }
            }
        }
        initializedoctors();
     }
    private void initializedoctors() {
        doctorJComboBox.removeAllItems();
        String selectedHospitalName = (String) HospitalJComboBox.getSelectedItem();
        for(Hospital hospital: this.city.getHospitals()) {
            if(hospital.getHospitalName().equalsIgnoreCase(selectedHospitalName)){
                this.hospital = hospital;
                
                for(Doctor doctor : hospital.getDoctors()){
                    doctorJComboBox.addItem(doctor.getSpecialization());
                }
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblchoosecity = new javax.swing.JLabel();
        cityJComboBox = new javax.swing.JComboBox<>();
        lblcommunity = new javax.swing.JLabel();
        HospitalJComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        lblhouse = new javax.swing.JLabel();
        doctorJComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UIPackage/healthpic5.jpeg"))); // NOI18N

        lblchoosecity.setText("City :");

        cityJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJComboBoxActionPerformed(evt);
            }
        });

        lblcommunity.setText("Hospital");

        HospitalJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalJComboBoxActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblhouse.setText("Doctor");

        doctorJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorJComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("For getting appointment click here---->");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblchoosecity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblhouse))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cityJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HospitalJComboBox, 0, 120, Short.MAX_VALUE)
                            .addComponent(doctorJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblchoosecity, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HospitalJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhouse, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cityJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJComboBoxActionPerformed
        initializehospitals();
    }//GEN-LAST:event_cityJComboBoxActionPerformed

    private void HospitalJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalJComboBoxActionPerformed
       initializehospitals();
    }//GEN-LAST:event_HospitalJComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedCityName = (String) cityJComboBox.getSelectedItem();
        String selectedHospitalName = (String) HospitalJComboBox.getSelectedItem();
        String selectedDoctorName = (String) doctorJComboBox.getSelectedItem();
         HospitalCity selectedCity = null;
        Hospital selectedHospital = null;
        Doctor selectedDoctor=null;
        
        for (HospitalCity city : system.getCities()){
            if (city.getCityName().equalsIgnoreCase(selectedCityName)){
                 selectedCity = city;
            }
        }      
        for (Hospital hospital : selectedCity.getHospitals()){
            if (hospital.getHospitalName().equalsIgnoreCase(selectedHospitalName)){
                selectedHospital = hospital;
            }
        }
        for (Doctor doctor : selectedHospital.getDoctors()){
            if (doctor.getName().equalsIgnoreCase(selectedDoctorName)){
                selectedDoctor = doctor;
            }
        }
       
        
        OPPanel2 panel = new OPPanel2(displayJpanel,system);
        displayJpanel.add("OUTPATIENT", panel);
        CardLayout layout = (CardLayout) displayJpanel.getLayout();
        layout.next(displayJpanel);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void doctorJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorJComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> HospitalJComboBox;
    private javax.swing.JComboBox<String> cityJComboBox;
    private javax.swing.JComboBox<String> doctorJComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblchoosecity;
    private javax.swing.JLabel lblcommunity;
    private javax.swing.JLabel lblhouse;
    // End of variables declaration//GEN-END:variables
}
