/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import healthcare.House;
import healthcare.Patient;
import healthcare.Person;
import java.awt.CardLayout;
import java.awt.Panel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mynenidivya
 */
public class PatientPanel extends javax.swing.JPanel {
    
    private healthcare.System System;
    private House House;
    private JPanel displayJPanel;

    /**
     * Creates new form PatientPanel
     */
    public PatientPanel(JPanel displayJPanel, House house) {
        initComponents();
        this.displayJPanel=displayJPanel;
        //this.system=system;
        this.House=house;
        populateTable();
        java.lang.System.out.println("Inside PersonPanel");
    }
    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) patientsJTable.getModel();
        model.setRowCount(0);
        
        for(Person person:House.getPersons()){
            Object[] row = new Object[4];
            row[0]=person;
            row[1]=person.getAge();
            row[2]=person.getGender();
            row[3]=person.isMarried();
            
            model.addRow(row);
        }
    }
    
    String regxPatientName = "^[a-zA-Z\\s]+$";
    String regxAge = "^[0-9]{0,2}+\\.?[0-9]{0,2}$";
    
    private String formateDate(Date date) {
       String Formate="yyyy-mm-dd hh:mm:ss";
       
       SimpleDateFormat Simple=new SimpleDateFormat(Formate);
       return Simple.format(date);
    }
     
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateJButton = new javax.swing.JButton();
        personsJLabel = new javax.swing.JLabel();
        deleteJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientsJTable = new javax.swing.JTable();
        chkbxmarried = new javax.swing.JCheckBox();
        txtgender = new javax.swing.JComboBox<>();
        addJButton = new javax.swing.JButton();
        lblcommunityName = new javax.swing.JLabel();
        lblpersonname = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        txtpatientname = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        View = new javax.swing.JButton();

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        personsJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        personsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        personsJLabel.setText("              For Doctors Only");

        deleteJButton.setText("Delete");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        patientsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Person Name", "Age", "Gender", "Married?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientsJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientsJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(patientsJTable);

        chkbxmarried.setText("Married ?");

        txtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        lblcommunityName.setText("Gender : ");

        lblpersonname.setText("Person Name : ");

        lblage.setText("Age :");

        txtpatientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientnameActionPerformed(evt);
            }
        });

        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblpersonname)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblcommunityName))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(lblage)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(personsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtpatientname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(chkbxmarried)))
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(View)
                .addGap(120, 120, 120))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(personsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpersonname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpatientname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcommunityName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(chkbxmarried)))
                .addGap(18, 18, 18)
                .addComponent(View)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJButton)
                    .addComponent(updateJButton)
                    .addComponent(deleteJButton))
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        int selectedRowIndex = patientsJTable.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) patientsJTable.getModel();
        Person person = (Person) model.getValueAt(selectedRowIndex, 0);

        if (person.getName().equals(txtpatientname.getText()) && String.valueOf(person.getAge()).equals(txtage.getText()) && person.getGender().equals(((String) txtgender.getSelectedItem())) && person.isMarried()==chkbxmarried.isSelected()) {
            JOptionPane.showMessageDialog(this, "No new values entered\nPlease enter a new details of the person");
            return;
        }else if (txtpatientname.getText().equals("") || txtage.getText().equals("")){
            JOptionPane.showMessageDialog(this, "House Name is blank\nPlease enter a valid person name");
            return;
        }
        else{
            if (txtpatientname.getText().matches(regxPatientName) && txtage.getText().matches(regxAge)){
                person.setName(txtpatientname.getText());
                person.setAge(Double.parseDouble(txtage.getText()));
                person.setGender((String) txtgender.getSelectedItem());
                person.setMarried(chkbxmarried.isSelected());

                JOptionPane.showMessageDialog(this, "Person updated successfully");
                populateTable();

                txtpatientname.setText("");
                txtgender.setSelectedIndex(0);
                txtage.setText("");
                chkbxmarried.setSelected(false);
            }else{
                JOptionPane.showMessageDialog(this, "Enter valid details\nOnly alphabets and spaces allowed for Person Name\nOnly numbers(<100) allowed for Age");
            }
        }
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        int selectedRowIndex = patientsJTable.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) patientsJTable.getModel();
        Person person = (Person) model.getValueAt(selectedRowIndex, 0);

        House.getPersons().remove(person);

        txtpatientname.setText("");
        txtgender.setSelectedIndex(0);
        txtage.setText("");
        chkbxmarried.setSelected(false);

        JOptionPane.showMessageDialog(this, "Person deleted successfully");
        populateTable();
    }//GEN-LAST:event_deleteJButtonActionPerformed

    private void patientsJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientsJTableMouseClicked
        int selectedRowIndex = patientsJTable.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) patientsJTable.getModel();
        Person person = (Person) model.getValueAt(selectedRowIndex, 0);

        txtpatientname.setText(person.getName());
        txtgender.setSelectedItem(person.getGender());
        txtage.setText(String.valueOf(person.getAge()));
        chkbxmarried.setSelected(person.isMarried());
    }//GEN-LAST:event_patientsJTableMouseClicked

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        if (txtpatientname.getText().isBlank() && txtage.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Please enter valid details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) patientsJTable.getModel();

        for(Person person:House.getPersons()){
            if (txtpatientname.getText().equals(person.getName())){
                JOptionPane.showMessageDialog(this, "Person name already exists\nPlease enter a different person name");
                return;
            }
        }
        String gender = (String) txtgender.getSelectedItem();
        if (gender.equals("Select")){
            gender = "";
        }

        if (txtpatientname.getText().matches(regxPatientName) && txtage.getText().matches(regxAge)){
            double age = txtage.getText().isBlank()?0:Double.parseDouble(txtage.getText());

            Person person = new Person(txtpatientname.getText(), age, gender, chkbxmarried.isSelected(),new Patient());
            House.getPersons().add(person);
            populateTable();

            txtpatientname.setText("");
            txtgender.setSelectedIndex(0);
            txtage.setText("");
            chkbxmarried.setSelected(false);
        }else{
            JOptionPane.showMessageDialog(this, "Please enter valid details");
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void txtpatientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientnameActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        // TODO add your handling code here:
         int selectedRow = patientsJTable.getSelectedRow();
        if(selectedRow <0){
            JOptionPane.showMessageDialog(this, "Please Select any Person to View his Medical History");
            return;
        }
        
        showPatientInfo(selectedRow);
    }                                         

    private void showPatientInfo(int selectedRow) {
        
        DefaultTableModel model = (DefaultTableModel) patientsJTable.getModel();
        Person person = (Person) model.getValueAt(selectedRow, 0);
        navigateToPatientHistory(person);
    }
    
    private void navigateToPatientHistory(Person person) {
        
        EncountersPanel encounterHistoryJPanel = new EncountersPanel(displayJPanel, person);
        displayJPanel.add("PatientHistory",encounterHistoryJPanel);
        CardLayout cardLayout = (CardLayout) displayJPanel.getLayout();
        cardLayout.next(displayJPanel);
    
    }//GEN-LAST:event_ViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton View;
    private javax.swing.JButton addJButton;
    private javax.swing.JCheckBox chkbxmarried;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblcommunityName;
    private javax.swing.JLabel lblpersonname;
    private javax.swing.JTable patientsJTable;
    private javax.swing.JLabel personsJLabel;
    private javax.swing.JTextField txtage;
    private javax.swing.JComboBox<String> txtgender;
    private javax.swing.JTextField txtpatientname;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
