/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIPackage;

import healthcare.City;
import healthcare.Community;
import healthcare.House;
import java.util.List;
import javax.swing.JPanel;
import healthcare.System;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mynenidivya
 */
public class Search extends javax.swing.JPanel {
     private JPanel displayJpanel;
    private System system;
    private City city;
    private Community community;
    

    /**
     * Creates new form Search
     */
    public Search(JPanel displayJpanel, System system) {
        initComponents();
        this.displayJpanel = displayJpanel;
        this.system = system;
        initializeCities();
        initializeCommunities();
    }
    private void initializeCities() {
        
        List<City> cities = system.getCities();
        for(City city:cities){
            cityJComboBox.addItem(city.getCityName());
        }
    }
    
    private void initializeCommunities() {
        communityJComboBox.removeAllItems();
        String selectedCityName = (String) cityJComboBox.getSelectedItem();
        for(City city : system.getCities()) {
            if(city.getCityName().equalsIgnoreCase(selectedCityName)){
                this.city = city;                
                for(Community community : city.getCommunities()){
                    communityJComboBox.addItem(community.getCommunityName());
                    
                }
            }
        }
        initializeHouses();
    }
    
    private void initializeHouses() {
        houseJComboBox.removeAllItems();
        String selectedCommunityName = (String) communityJComboBox.getSelectedItem();
        for(Community community : this.city.getCommunities()) {
            if(community.getCommunityName().equalsIgnoreCase(selectedCommunityName)){
                this.community = community;
                
                for(House house : community.getHouses()){
                    houseJComboBox.addItem(house.getHouseName());
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblhouse = new javax.swing.JLabel();
        houseJComboBox = new javax.swing.JComboBox<>();
        lblchoosecity = new javax.swing.JLabel();
        cityJComboBox = new javax.swing.JComboBox<>();
        lblcommunity = new javax.swing.JLabel();
        communityJComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        lblhouse.setText("House :");

        houseJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                houseJComboBoxActionPerformed(evt);
            }
        });

        lblchoosecity.setText("City :");

        cityJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJComboBoxActionPerformed(evt);
            }
        });

        lblcommunity.setText("Community :");

        communityJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityJComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblchoosecity, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(cityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcommunity)
                                    .addComponent(lblhouse))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(communityJComboBox, 0, 121, Short.MAX_VALUE)
                                    .addComponent(houseJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1)))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblchoosecity, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(communityJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(houseJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhouse, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void houseJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_houseJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_houseJComboBoxActionPerformed

    private void cityJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJComboBoxActionPerformed
        initializeCommunities();
    }//GEN-LAST:event_cityJComboBoxActionPerformed

    private void communityJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityJComboBoxActionPerformed
        initializeHouses();
    }//GEN-LAST:event_communityJComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selectedCityName = (String) cityJComboBox.getSelectedItem();
        String selectedCommunityName = (String) communityJComboBox.getSelectedItem();
        String selectedHouseName = (String) houseJComboBox.getSelectedItem();
        City selectedCity = null;
        Community selectedCommunity = null;
        House selectedHouse = null;
        for (City city : system.getCities()){
            if (city.getCityName().equalsIgnoreCase(selectedCityName)){
                 selectedCity = city;
            }
        }      
        for (Community community : selectedCity.getCommunities()){
            if (community.getCommunityName().equalsIgnoreCase(selectedCommunityName)){
                selectedCommunity = community;
            }
        }
        
        for (House house : selectedCommunity.getHouses()){
            if (house.getHouseName().equalsIgnoreCase(selectedHouseName)){
                selectedHouse = house;
            }
        }
         PatientPanel personPanel = new PatientPanel(displayJpanel,selectedHouseName,selectedCommunity);
        displayJpanel.add("PersonsInformation", personPanel);
        CardLayout cardLayout = (CardLayout) displayJpanel.getLayout();
        cardLayout.next(displayJpanel);
        
        
        
                                           

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cityJComboBox;
    private javax.swing.JComboBox<String> communityJComboBox;
    private javax.swing.JComboBox<String> houseJComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblchoosecity;
    private javax.swing.JLabel lblcommunity;
    private javax.swing.JLabel lblhouse;
    // End of variables declaration//GEN-END:variables
}
